### PR TITLE
Fixes crash with qualified name for entity node

### LINKED ISSUE #14: Crash with invalid xml
Following xml causing a crash:
```
<?xml version="1.0"?>
<!DOCTYPE EXAMPLE SYSTEM "example.dtd" [
<!ENTITY xml "<prefix:node>prefix is indeclared here</prefix:node>">
]>
<EXAMPLE xmlns:prefix="http://example.com">
  &xml;
</EXAMPLE>
```

Actually in debug version following assert https://github.com/graetzer/GDataXML-HTML/blob/master/Pod/Classes/GDataXMLNode.m#L375-L379 will fail:
```
- (NSString *)stringFromXMLString:(const xmlChar *)chars {
    
#if DEBUG
    NSCAssert(chars != NULL, @"GDataXMLNode sees an unexpected empty string");
#endif
    if (chars == NULL) return nil;
```

If we remove it (or use a release version) lib will crash later on in https://github.com/graetzer/GDataXML-HTML/blob/master/Pod/Classes/GDataXMLNode.m#L582-L586 in the `if` check:

```
  if (asprintf(&qname, "%s:%s", (const char *)xmlNode_->ns->prefix,
                         xmlNode_->name) != -1) {
                str = [self stringFromXMLString:(const xmlChar *)qname];
                free(qname);
            }
```

### PR DESCRIPTION
**Pull request by artemyarulin**
Fixes #14

### CODE REVIEW

**Comment by graetzer** [comment]
Seems finde to me, if you want you can merge it

**Comment by graetzer** [comment]
But why is the travis build not passing?

**Comment by artemyarulin** [comment]
Hm, weird.

ns-crash/build21 is broken because it has only the test for the error
ns-crash/build22 has a fix and passed as it should be
PR/build23 - just a pull request of the same branch and failed, wtf
main/build24 - but when it was merged to the master everything went ok

I'll try to re-run build 23 and see

**Comment by artemyarulin** [comment]
Well, pull request was accepted and removed so Travis cannot find it and re-build. 

Don't know what else I can do here. Master is stable at least

**Pull request merged**
