### PR TITLE
add support for swift pod

### PR DESCRIPTION
**Pull request by IvanChan**
#import <libxml/tree.h>
#import <libxml/parser.h>
#import <libxml/xmlstring.h>
#import <libxml/HTMLparser.h>
#import <libxml/xpath.h>
#import <libxml/xpathInternals.h>

Headers import above in .h will fail the pod for swift project, just hide those libxml things to .m will satisfy swift pod.

Further more,  the module map is useless

### CODE REVIEW

**Comment by artemyarulin** [comment]
Thanks!

**Comment by IvanChan** [comment]
Will you release a new tag and push for cocoapods?

**Comment by artemyarulin** [comment]
Ahm, not sure I have an access to that, @graetzer can you do that?

**Comment by graetzer** [comment]
Hm I'll need to check that

**Comment by graetzer** [comment]
done, @artemyarulin can you verify the published version works ?

**Comment by artemyarulin** [comment]
omg, I haven't done iOS development like for couple of years 😄 Sorry, would take ages to check it. @IvanChan can you please check?

**Comment by IvanChan** [comment]
I create a objective-c/swift project with pod, try like below
    pod 'GDataXML-HTML', :git => 'https://github.com/graetzer/GDataXML-HTML.git', :branch=>'master'

both work well

**Pull request merged**
